// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_website.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAverageWebsiteSession = `-- name: GetAverageWebsiteSession :one
SELECT COALESCE(AVG(avg_session_duration), 0)::BIGINT AS average_website_session
FROM analytics_site_stats
    left join sources on analytics_site_stats.source_id = sources.id
where sources.user_id = $1
`

func (q *Queries) GetAverageWebsiteSession(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAverageWebsiteSession, userID)
	var average_website_session int64
	err := row.Scan(&average_website_session)
	return average_website_session, err
}

const getSiteStatsOverTime = `-- name: GetSiteStatsOverTime :many
SELECT date_str, total_visitors, avg_session_duration
FROM (
        SELECT TO_CHAR(DATE_TRUNC('week', date), 'IYYY-"W"IW') as date_str,
            COALESCE(SUM(visitors), 0)::BIGINT as total_visitors,
            COALESCE(AVG(avg_session_duration), 0)::FLOAT as avg_session_duration
        FROM analytics_site_stats ass
            JOIN sources s ON ass.source_id = s.id
        WHERE s.user_id = $1
        GROUP BY DATE_TRUNC('week', date)
        ORDER BY DATE_TRUNC('week', date) DESC
        LIMIT 52
    ) recent_weeks
ORDER BY date_str ASC
`

type GetSiteStatsOverTimeRow struct {
	DateStr            string  `json:"date_str"`
	TotalVisitors      int64   `json:"total_visitors"`
	AvgSessionDuration float64 `json:"avg_session_duration"`
}

func (q *Queries) GetSiteStatsOverTime(ctx context.Context, userID uuid.UUID) ([]GetSiteStatsOverTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getSiteStatsOverTime, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSiteStatsOverTimeRow
	for rows.Next() {
		var i GetSiteStatsOverTimeRow
		if err := rows.Scan(&i.DateStr, &i.TotalVisitors, &i.AvgSessionDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPagesByViews = `-- name: GetTopPagesByViews :many
SELECT url_path,
    COALESCE(SUM(views), 0)::BIGINT as total_views
FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
WHERE s.user_id = $1
GROUP BY url_path
ORDER BY total_views DESC
LIMIT 50
`

type GetTopPagesByViewsRow struct {
	UrlPath    string `json:"url_path"`
	TotalViews int64  `json:"total_views"`
}

func (q *Queries) GetTopPagesByViews(ctx context.Context, userID uuid.UUID) ([]GetTopPagesByViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopPagesByViews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPagesByViewsRow
	for rows.Next() {
		var i GetTopPagesByViewsRow
		if err := rows.Scan(&i.UrlPath, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPageViews = `-- name: GetTotalPageViews :one
SELECT COALESCE(SUM(views), 0)::BIGINT AS total_page_views
FROM analytics_page_stats
    left join sources on analytics_page_stats.source_id = sources.id
where sources.user_id = $1
`

func (q *Queries) GetTotalPageViews(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPageViews, userID)
	var total_page_views int64
	err := row.Scan(&total_page_views)
	return total_page_views, err
}

const getTotalSiteStats = `-- name: GetTotalSiteStats :one
SELECT COALESCE(SUM(visitors), 0)::BIGINT AS total_visitors
FROM analytics_site_stats
    left join sources on analytics_site_stats.source_id = sources.id
where sources.user_id = $1
`

func (q *Queries) GetTotalSiteStats(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSiteStats, userID)
	var total_visitors int64
	err := row.Scan(&total_visitors)
	return total_visitors, err
}
