// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_tags.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getClassificationAnalytics = `-- name: GetClassificationAnalytics :many
SELECT tc.id as classification_id,
    tc.name as classification_name,
    COUNT(DISTINCT p.id)::BIGINT as post_count,
    COALESCE(AVG(prh.likes), 0)::BIGINT as avg_likes,
    COALESCE(AVG(prh.reposts), 0)::BIGINT as avg_reposts,
    COALESCE(AVG(prh.views), 0)::BIGINT as avg_views,
    COALESCE(SUM(prh.likes), 0)::BIGINT as total_likes,
    COALESCE(SUM(prh.views), 0)::BIGINT as total_views
FROM tag_classifications tc
    JOIN tags t ON tc.id = t.classification_id
    JOIN post_tags pt ON t.id = pt.tag_id
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    LEFT JOIN (
        SELECT DISTINCT ON (post_id) post_id,
            likes,
            reposts,
            views
        FROM posts_reactions_history
        ORDER BY post_id,
            synced_at DESC
    ) prh ON p.id = prh.post_id
WHERE tc.user_id = $1
GROUP BY tc.id, tc.name
ORDER BY avg_likes DESC
`

type GetClassificationAnalyticsRow struct {
	ClassificationID   uuid.UUID `json:"classification_id"`
	ClassificationName string    `json:"classification_name"`
	PostCount          int64     `json:"post_count"`
	AvgLikes           int64     `json:"avg_likes"`
	AvgReposts         int64     `json:"avg_reposts"`
	AvgViews           int64     `json:"avg_views"`
	TotalLikes         int64     `json:"total_likes"`
	TotalViews         int64     `json:"total_views"`
}

func (q *Queries) GetClassificationAnalytics(ctx context.Context, userID uuid.UUID) ([]GetClassificationAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassificationAnalytics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassificationAnalyticsRow
	for rows.Next() {
		var i GetClassificationAnalyticsRow
		if err := rows.Scan(
			&i.ClassificationID,
			&i.ClassificationName,
			&i.PostCount,
			&i.AvgLikes,
			&i.AvgReposts,
			&i.AvgViews,
			&i.TotalLikes,
			&i.TotalViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassificationAnalyticsFiltered = `-- name: GetClassificationAnalyticsFiltered :many
SELECT tc.id as classification_id,
    tc.name as classification_name,
    COUNT(DISTINCT p.id)::BIGINT as post_count,
    COALESCE(AVG(prh.likes), 0)::BIGINT as avg_likes,
    COALESCE(AVG(prh.reposts), 0)::BIGINT as avg_reposts,
    COALESCE(AVG(prh.views), 0)::BIGINT as avg_views,
    COALESCE(SUM(prh.likes), 0)::BIGINT as total_likes,
    COALESCE(SUM(prh.views), 0)::BIGINT as total_views
FROM tag_classifications tc
    JOIN tags t ON tc.id = t.classification_id
    JOIN post_tags pt ON t.id = pt.tag_id
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    LEFT JOIN (
        SELECT DISTINCT ON (post_id) post_id,
            likes,
            reposts,
            views
        FROM posts_reactions_history
        ORDER BY post_id,
            synced_at DESC
    ) prh ON p.id = prh.post_id
WHERE tc.user_id = $1
    AND ($2::date IS NULL OR p.created_at >= $2::date)
    AND ($3::date IS NULL OR p.created_at < $3::date + INTERVAL '1 day')
    AND (array_length($4::text[], 1) IS NULL OR p.post_type = ANY($4::text[]))
GROUP BY tc.id, tc.name
ORDER BY avg_likes DESC
`

type GetClassificationAnalyticsFilteredParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
	PostTypes []string     `json:"post_types"`
}

type GetClassificationAnalyticsFilteredRow struct {
	ClassificationID   uuid.UUID `json:"classification_id"`
	ClassificationName string    `json:"classification_name"`
	PostCount          int64     `json:"post_count"`
	AvgLikes           int64     `json:"avg_likes"`
	AvgReposts         int64     `json:"avg_reposts"`
	AvgViews           int64     `json:"avg_views"`
	TotalLikes         int64     `json:"total_likes"`
	TotalViews         int64     `json:"total_views"`
}

func (q *Queries) GetClassificationAnalyticsFiltered(ctx context.Context, arg GetClassificationAnalyticsFilteredParams) ([]GetClassificationAnalyticsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassificationAnalyticsFiltered,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		pq.Array(arg.PostTypes),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassificationAnalyticsFilteredRow
	for rows.Next() {
		var i GetClassificationAnalyticsFilteredRow
		if err := rows.Scan(
			&i.ClassificationID,
			&i.ClassificationName,
			&i.PostCount,
			&i.AvgLikes,
			&i.AvgReposts,
			&i.AvgViews,
			&i.TotalLikes,
			&i.TotalViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagAnalytics = `-- name: GetTagAnalytics :many
SELECT t.id as tag_id,
    t.name as tag_name,
    tc.name as classification_name,
    COUNT(DISTINCT p.id)::BIGINT as post_count,
    COALESCE(AVG(prh.likes), 0)::BIGINT as avg_likes,
    COALESCE(AVG(prh.reposts), 0)::BIGINT as avg_reposts,
    COALESCE(AVG(prh.views), 0)::BIGINT as avg_views,
    COALESCE(SUM(prh.likes), 0)::BIGINT as total_likes,
    COALESCE(SUM(prh.views), 0)::BIGINT as total_views
FROM tags t
    LEFT JOIN tag_classifications tc ON t.classification_id = tc.id
    JOIN post_tags pt ON t.id = pt.tag_id
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    LEFT JOIN (
        SELECT DISTINCT ON (post_id) post_id,
            likes,
            reposts,
            views
        FROM posts_reactions_history
        ORDER BY post_id,
            synced_at DESC
    ) prh ON p.id = prh.post_id
WHERE s.user_id = $1
GROUP BY t.id, t.name, tc.name
ORDER BY avg_likes DESC
`

type GetTagAnalyticsRow struct {
	TagID              uuid.UUID      `json:"tag_id"`
	TagName            string         `json:"tag_name"`
	ClassificationName sql.NullString `json:"classification_name"`
	PostCount          int64          `json:"post_count"`
	AvgLikes           int64          `json:"avg_likes"`
	AvgReposts         int64          `json:"avg_reposts"`
	AvgViews           int64          `json:"avg_views"`
	TotalLikes         int64          `json:"total_likes"`
	TotalViews         int64          `json:"total_views"`
}

func (q *Queries) GetTagAnalytics(ctx context.Context, userID uuid.UUID) ([]GetTagAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagAnalytics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagAnalyticsRow
	for rows.Next() {
		var i GetTagAnalyticsRow
		if err := rows.Scan(
			&i.TagID,
			&i.TagName,
			&i.ClassificationName,
			&i.PostCount,
			&i.AvgLikes,
			&i.AvgReposts,
			&i.AvgViews,
			&i.TotalLikes,
			&i.TotalViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagAnalyticsFiltered = `-- name: GetTagAnalyticsFiltered :many
SELECT t.id as tag_id,
    t.name as tag_name,
    tc.name as classification_name,
    COUNT(DISTINCT p.id)::BIGINT as post_count,
    COALESCE(AVG(prh.likes), 0)::BIGINT as avg_likes,
    COALESCE(AVG(prh.reposts), 0)::BIGINT as avg_reposts,
    COALESCE(AVG(prh.views), 0)::BIGINT as avg_views,
    COALESCE(SUM(prh.likes), 0)::BIGINT as total_likes,
    COALESCE(SUM(prh.views), 0)::BIGINT as total_views
FROM tags t
    LEFT JOIN tag_classifications tc ON t.classification_id = tc.id
    JOIN post_tags pt ON t.id = pt.tag_id
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    LEFT JOIN (
        SELECT DISTINCT ON (post_id) post_id,
            likes,
            reposts,
            views
        FROM posts_reactions_history
        ORDER BY post_id,
            synced_at DESC
    ) prh ON p.id = prh.post_id
WHERE s.user_id = $1
    AND ($2::date IS NULL OR p.created_at >= $2::date)
    AND ($3::date IS NULL OR p.created_at < $3::date + INTERVAL '1 day')
    AND (array_length($4::text[], 1) IS NULL OR p.post_type = ANY($4::text[]))
GROUP BY t.id, t.name, tc.name
ORDER BY avg_likes DESC
`

type GetTagAnalyticsFilteredParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
	PostTypes []string     `json:"post_types"`
}

type GetTagAnalyticsFilteredRow struct {
	TagID              uuid.UUID      `json:"tag_id"`
	TagName            string         `json:"tag_name"`
	ClassificationName sql.NullString `json:"classification_name"`
	PostCount          int64          `json:"post_count"`
	AvgLikes           int64          `json:"avg_likes"`
	AvgReposts         int64          `json:"avg_reposts"`
	AvgViews           int64          `json:"avg_views"`
	TotalLikes         int64          `json:"total_likes"`
	TotalViews         int64          `json:"total_views"`
}

func (q *Queries) GetTagAnalyticsFiltered(ctx context.Context, arg GetTagAnalyticsFilteredParams) ([]GetTagAnalyticsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagAnalyticsFiltered,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		pq.Array(arg.PostTypes),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagAnalyticsFilteredRow
	for rows.Next() {
		var i GetTagAnalyticsFilteredRow
		if err := rows.Scan(
			&i.TagID,
			&i.TagName,
			&i.ClassificationName,
			&i.PostCount,
			&i.AvgLikes,
			&i.AvgReposts,
			&i.AvgViews,
			&i.TotalLikes,
			&i.TotalViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
