// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_website.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAverageWebsiteSession = `-- name: GetAverageWebsiteSession :one
SELECT COALESCE(AVG(avg_session_duration), 0)::BIGINT AS average_website_session
FROM analytics_site_stats
    LEFT JOIN sources ON analytics_site_stats.source_id = sources.id
WHERE sources.user_id = $1
    AND analytics_site_stats.analytics_type = 'ga'
`

func (q *Queries) GetAverageWebsiteSession(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAverageWebsiteSession, userID)
	var average_website_session int64
	err := row.Scan(&average_website_session)
	return average_website_session, err
}

const getGSCSiteStatsOverTime = `-- name: GetGSCSiteStatsOverTime :many
SELECT date_str, total_clicks, total_impressions
FROM (
        SELECT TO_CHAR(DATE_TRUNC('week', date), 'IYYY-"W"IW') as date_str,
            COALESCE(SUM(visitors), 0)::BIGINT as total_clicks,
            COALESCE(SUM(impressions), 0)::BIGINT as total_impressions
        FROM analytics_site_stats ass
            JOIN sources s ON ass.source_id = s.id
        WHERE s.user_id = $1
            AND ass.analytics_type = 'gsc'
        GROUP BY DATE_TRUNC('week', date)
        ORDER BY DATE_TRUNC('week', date) DESC
        LIMIT 52
    ) recent_weeks
ORDER BY date_str ASC
`

type GetGSCSiteStatsOverTimeRow struct {
	DateStr          string `json:"date_str"`
	TotalClicks      int64  `json:"total_clicks"`
	TotalImpressions int64  `json:"total_impressions"`
}

func (q *Queries) GetGSCSiteStatsOverTime(ctx context.Context, userID uuid.UUID) ([]GetGSCSiteStatsOverTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getGSCSiteStatsOverTime, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGSCSiteStatsOverTimeRow
	for rows.Next() {
		var i GetGSCSiteStatsOverTimeRow
		if err := rows.Scan(&i.DateStr, &i.TotalClicks, &i.TotalImpressions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGSCTopPagesByClicks = `-- name: GetGSCTopPagesByClicks :many
SELECT url_path,
    COALESCE(SUM(views), 0)::BIGINT as total_clicks,
    COALESCE(SUM(impressions), 0)::BIGINT as total_impressions
FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
WHERE s.user_id = $1
    AND aps.analytics_type = 'gsc'
GROUP BY url_path
ORDER BY total_clicks DESC
LIMIT 50
`

type GetGSCTopPagesByClicksRow struct {
	UrlPath          string `json:"url_path"`
	TotalClicks      int64  `json:"total_clicks"`
	TotalImpressions int64  `json:"total_impressions"`
}

func (q *Queries) GetGSCTopPagesByClicks(ctx context.Context, userID uuid.UUID) ([]GetGSCTopPagesByClicksRow, error) {
	rows, err := q.db.QueryContext(ctx, getGSCTopPagesByClicks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGSCTopPagesByClicksRow
	for rows.Next() {
		var i GetGSCTopPagesByClicksRow
		if err := rows.Scan(&i.UrlPath, &i.TotalClicks, &i.TotalImpressions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteStatsOverTime = `-- name: GetSiteStatsOverTime :many
SELECT date_str, total_visitors, avg_session_duration
FROM (
        SELECT TO_CHAR(DATE_TRUNC('week', date), 'IYYY-"W"IW') as date_str,
            COALESCE(SUM(visitors), 0)::BIGINT as total_visitors,
            COALESCE(AVG(avg_session_duration), 0)::FLOAT as avg_session_duration
        FROM analytics_site_stats ass
            JOIN sources s ON ass.source_id = s.id
        WHERE s.user_id = $1
            AND ass.analytics_type = 'ga'
        GROUP BY DATE_TRUNC('week', date)
        ORDER BY DATE_TRUNC('week', date) DESC
        LIMIT 52
    ) recent_weeks
ORDER BY date_str ASC
`

type GetSiteStatsOverTimeRow struct {
	DateStr            string  `json:"date_str"`
	TotalVisitors      int64   `json:"total_visitors"`
	AvgSessionDuration float64 `json:"avg_session_duration"`
}

func (q *Queries) GetSiteStatsOverTime(ctx context.Context, userID uuid.UUID) ([]GetSiteStatsOverTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getSiteStatsOverTime, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSiteStatsOverTimeRow
	for rows.Next() {
		var i GetSiteStatsOverTimeRow
		if err := rows.Scan(&i.DateStr, &i.TotalVisitors, &i.AvgSessionDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteStatsOverTimeFiltered = `-- name: GetSiteStatsOverTimeFiltered :many
SELECT date_str, total_visitors, avg_session_duration
FROM (
        SELECT TO_CHAR(DATE_TRUNC('week', date), 'IYYY-"W"IW') as date_str,
            COALESCE(SUM(visitors), 0)::BIGINT as total_visitors,
            COALESCE(AVG(avg_session_duration), 0)::FLOAT as avg_session_duration
        FROM analytics_site_stats ass
            JOIN sources s ON ass.source_id = s.id
        WHERE s.user_id = $1
            AND ass.analytics_type = 'ga'
            AND ($2::date IS NULL OR ass.date >= $2::date)
            AND ($3::date IS NULL OR ass.date <= $3::date)
        GROUP BY DATE_TRUNC('week', date)
        ORDER BY DATE_TRUNC('week', date) DESC
        LIMIT 52
    ) recent_weeks
ORDER BY date_str ASC
`

type GetSiteStatsOverTimeFilteredParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type GetSiteStatsOverTimeFilteredRow struct {
	DateStr            string  `json:"date_str"`
	TotalVisitors      int64   `json:"total_visitors"`
	AvgSessionDuration float64 `json:"avg_session_duration"`
}

func (q *Queries) GetSiteStatsOverTimeFiltered(ctx context.Context, arg GetSiteStatsOverTimeFilteredParams) ([]GetSiteStatsOverTimeFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getSiteStatsOverTimeFiltered, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSiteStatsOverTimeFilteredRow
	for rows.Next() {
		var i GetSiteStatsOverTimeFilteredRow
		if err := rows.Scan(&i.DateStr, &i.TotalVisitors, &i.AvgSessionDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPagesByViews = `-- name: GetTopPagesByViews :many
SELECT url_path,
    COALESCE(SUM(views), 0)::BIGINT as total_views
FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
WHERE s.user_id = $1
    AND aps.analytics_type = 'ga'
GROUP BY url_path
ORDER BY total_views DESC
LIMIT 50
`

type GetTopPagesByViewsRow struct {
	UrlPath    string `json:"url_path"`
	TotalViews int64  `json:"total_views"`
}

func (q *Queries) GetTopPagesByViews(ctx context.Context, userID uuid.UUID) ([]GetTopPagesByViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopPagesByViews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPagesByViewsRow
	for rows.Next() {
		var i GetTopPagesByViewsRow
		if err := rows.Scan(&i.UrlPath, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPagesByViewsFiltered = `-- name: GetTopPagesByViewsFiltered :many
SELECT url_path,
    COALESCE(SUM(views), 0)::BIGINT as total_views
FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
WHERE s.user_id = $1
    AND aps.analytics_type = 'ga'
    AND ($2::date IS NULL OR aps.date >= $2::date)
    AND ($3::date IS NULL OR aps.date <= $3::date)
GROUP BY url_path
ORDER BY total_views DESC
LIMIT 50
`

type GetTopPagesByViewsFilteredParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type GetTopPagesByViewsFilteredRow struct {
	UrlPath    string `json:"url_path"`
	TotalViews int64  `json:"total_views"`
}

func (q *Queries) GetTopPagesByViewsFiltered(ctx context.Context, arg GetTopPagesByViewsFilteredParams) ([]GetTopPagesByViewsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopPagesByViewsFiltered, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPagesByViewsFilteredRow
	for rows.Next() {
		var i GetTopPagesByViewsFilteredRow
		if err := rows.Scan(&i.UrlPath, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPageViews = `-- name: GetTotalPageViews :one
SELECT COALESCE(SUM(views), 0)::BIGINT AS total_page_views
FROM analytics_page_stats
    LEFT JOIN sources ON analytics_page_stats.source_id = sources.id
WHERE sources.user_id = $1
    AND analytics_page_stats.analytics_type = 'ga'
`

func (q *Queries) GetTotalPageViews(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPageViews, userID)
	var total_page_views int64
	err := row.Scan(&total_page_views)
	return total_page_views, err
}

const getTotalSiteStats = `-- name: GetTotalSiteStats :one
SELECT COALESCE(SUM(visitors), 0)::BIGINT AS total_visitors
FROM analytics_site_stats
    LEFT JOIN sources ON analytics_site_stats.source_id = sources.id
WHERE sources.user_id = $1
    AND analytics_site_stats.analytics_type = 'ga'
`

func (q *Queries) GetTotalSiteStats(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSiteStats, userID)
	var total_visitors int64
	err := row.Scan(&total_visitors)
	return total_visitors, err
}
