// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (id, created_at, user_id, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, user_id, token_hash, last_used_at
`

type CreateApiTokenParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createApiToken,
		arg.ID,
		arg.CreatedAt,
		arg.UserID,
		arg.TokenHash,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteApiTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteApiToken, arg.ID, arg.UserID)
	return err
}

const deleteApiTokensByUser = `-- name: DeleteApiTokensByUser :exec
DELETE FROM api_tokens WHERE user_id = $1
`

func (q *Queries) DeleteApiTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApiTokensByUser, userID)
	return err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT id, created_at, user_id, token_hash, last_used_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const getApiTokensByUser = `-- name: GetApiTokensByUser :many
SELECT id, created_at, user_id, token_hash, last_used_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetApiTokensByUser(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, getApiTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.TokenHash,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiTokenLastUsed = `-- name: UpdateApiTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = $2 WHERE id = $1
`

type UpdateApiTokenLastUsedParams struct {
	ID         uuid.UUID    `json:"id"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

func (q *Queries) UpdateApiTokenLastUsed(ctx context.Context, arg UpdateApiTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateApiTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
