// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const backupDeleteAnalyticsPageStatsForUser = `-- name: BackupDeleteAnalyticsPageStatsForUser :exec
DELETE FROM analytics_page_stats WHERE id IN (
    SELECT aps.id FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteAnalyticsPageStatsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteAnalyticsPageStatsForUser, userID)
	return err
}

const backupDeleteAnalyticsPageStatsOnTargetForUser = `-- name: BackupDeleteAnalyticsPageStatsOnTargetForUser :exec
DELETE FROM analytics_page_stats_on_target WHERE stat_id IN (
    SELECT aps.id FROM analytics_page_stats aps
    JOIN sources s ON aps.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteAnalyticsPageStatsOnTargetForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteAnalyticsPageStatsOnTargetForUser, userID)
	return err
}

const backupDeleteAnalyticsSiteStatsForUser = `-- name: BackupDeleteAnalyticsSiteStatsForUser :exec
DELETE FROM analytics_site_stats WHERE id IN (
    SELECT ass.id FROM analytics_site_stats ass
    JOIN sources s ON ass.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteAnalyticsSiteStatsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteAnalyticsSiteStatsForUser, userID)
	return err
}

const backupDeleteAnalyticsSiteStatsOnTargetForUser = `-- name: BackupDeleteAnalyticsSiteStatsOnTargetForUser :exec
DELETE FROM analytics_site_stats_on_target WHERE stat_id IN (
    SELECT ass.id FROM analytics_site_stats ass
    JOIN sources s ON ass.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteAnalyticsSiteStatsOnTargetForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteAnalyticsSiteStatsOnTargetForUser, userID)
	return err
}

const backupDeleteExclusionsForUser = `-- name: BackupDeleteExclusionsForUser :exec
DELETE FROM exclusions WHERE id IN (
    SELECT e.id FROM exclusions e
    JOIN sources s ON e.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteExclusionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteExclusionsForUser, userID)
	return err
}

const backupDeleteExportsForUser = `-- name: BackupDeleteExportsForUser :exec
DELETE FROM exports WHERE user_id = $1
`

func (q *Queries) BackupDeleteExportsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteExportsForUser, userID)
	return err
}

const backupDeleteLogsForUser = `-- name: BackupDeleteLogsForUser :exec
DELETE FROM logs WHERE source_id IN (
    SELECT s.id FROM sources s WHERE s.user_id = $1
) OR target_id IN (
    SELECT t.id FROM targets t WHERE t.user_id = $1
)
`

func (q *Queries) BackupDeleteLogsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteLogsForUser, userID)
	return err
}

const backupDeletePostTagsForUser = `-- name: BackupDeletePostTagsForUser :exec
DELETE FROM post_tags WHERE id IN (
    SELECT pt.id FROM post_tags pt
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeletePostTagsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeletePostTagsForUser, userID)
	return err
}

const backupDeletePostsForUser = `-- name: BackupDeletePostsForUser :exec
DELETE FROM posts WHERE id IN (
    SELECT p.id FROM posts p
    JOIN sources s ON p.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeletePostsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeletePostsForUser, userID)
	return err
}

const backupDeletePostsOnTargetForUser = `-- name: BackupDeletePostsOnTargetForUser :exec
DELETE FROM posts_on_target WHERE post_id IN (
    SELECT p.id FROM posts p
    JOIN sources s ON p.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeletePostsOnTargetForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeletePostsOnTargetForUser, userID)
	return err
}

const backupDeleteReactionsForUser = `-- name: BackupDeleteReactionsForUser :exec
DELETE FROM posts_reactions_history WHERE id IN (
    SELECT prh.id FROM posts_reactions_history prh
    JOIN posts p ON prh.post_id = p.id
    JOIN sources s ON p.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteReactionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteReactionsForUser, userID)
	return err
}

const backupDeleteRedirectsForUser = `-- name: BackupDeleteRedirectsForUser :exec
DELETE FROM redirects WHERE id IN (
    SELECT r.id FROM redirects r
    JOIN sources s ON r.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteRedirectsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteRedirectsForUser, userID)
	return err
}

const backupDeleteSourcesForUser = `-- name: BackupDeleteSourcesForUser :exec
DELETE FROM sources WHERE user_id = $1
`

func (q *Queries) BackupDeleteSourcesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteSourcesForUser, userID)
	return err
}

const backupDeleteSourcesOnTargetForUser = `-- name: BackupDeleteSourcesOnTargetForUser :exec
DELETE FROM sources_on_target WHERE source_id IN (
    SELECT s.id FROM sources s
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteSourcesOnTargetForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteSourcesOnTargetForUser, userID)
	return err
}

const backupDeleteSourcesStatsForUser = `-- name: BackupDeleteSourcesStatsForUser :exec
DELETE FROM sources_stats WHERE id IN (
    SELECT ss.id FROM sources_stats ss
    JOIN sources s ON ss.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteSourcesStatsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteSourcesStatsForUser, userID)
	return err
}

const backupDeleteSourcesStatsOnTargetForUser = `-- name: BackupDeleteSourcesStatsOnTargetForUser :exec
DELETE FROM sources_stats_on_target WHERE stat_id IN (
    SELECT ss.id FROM sources_stats ss
    JOIN sources s ON ss.source_id = s.id
    WHERE s.user_id = $1
)
`

func (q *Queries) BackupDeleteSourcesStatsOnTargetForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteSourcesStatsOnTargetForUser, userID)
	return err
}

const backupDeleteTableMappingsForUser = `-- name: BackupDeleteTableMappingsForUser :exec
DELETE FROM table_mappings WHERE target_id IN (
    SELECT t.id FROM targets t
    WHERE t.user_id = $1
)
`

func (q *Queries) BackupDeleteTableMappingsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteTableMappingsForUser, userID)
	return err
}

const backupDeleteTagClassificationsForUser = `-- name: BackupDeleteTagClassificationsForUser :exec
DELETE FROM tag_classifications WHERE user_id = $1
`

func (q *Queries) BackupDeleteTagClassificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteTagClassificationsForUser, userID)
	return err
}

const backupDeleteTagsForUser = `-- name: BackupDeleteTagsForUser :exec
DELETE FROM tags WHERE user_id = $1
`

func (q *Queries) BackupDeleteTagsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteTagsForUser, userID)
	return err
}

const backupDeleteTargetsForUser = `-- name: BackupDeleteTargetsForUser :exec
DELETE FROM targets WHERE user_id = $1
`

func (q *Queries) BackupDeleteTargetsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteTargetsForUser, userID)
	return err
}

const backupDeleteTokensForUser = `-- name: BackupDeleteTokensForUser :exec
DELETE FROM tokens WHERE id IN (
    SELECT t.id FROM tokens t
    LEFT JOIN sources s ON t.source_id = s.id
    LEFT JOIN targets tgt ON t.target_id = tgt.id
    WHERE s.user_id = $1 OR tgt.user_id = $1
)
`

func (q *Queries) BackupDeleteTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, backupDeleteTokensForUser, userID)
	return err
}

const backupGetAnalyticsPageStatsForUser = `-- name: BackupGetAnalyticsPageStatsForUser :many
SELECT aps.id, aps.date, aps.url_path, aps.views, aps.source_id, aps.analytics_type, aps.impressions FROM analytics_page_stats aps
JOIN sources s ON aps.source_id = s.id
WHERE s.user_id = $1
ORDER BY aps.date
`

func (q *Queries) BackupGetAnalyticsPageStatsForUser(ctx context.Context, userID uuid.UUID) ([]AnalyticsPageStat, error) {
	rows, err := q.db.QueryContext(ctx, backupGetAnalyticsPageStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsPageStat
	for rows.Next() {
		var i AnalyticsPageStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
			&i.AnalyticsType,
			&i.Impressions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetAnalyticsSiteStatsForUser = `-- name: BackupGetAnalyticsSiteStatsForUser :many
SELECT ass.id, ass.date, ass.visitors, ass.avg_session_duration, ass.source_id, ass.analytics_type, ass.impressions FROM analytics_site_stats ass
JOIN sources s ON ass.source_id = s.id
WHERE s.user_id = $1
ORDER BY ass.date
`

func (q *Queries) BackupGetAnalyticsSiteStatsForUser(ctx context.Context, userID uuid.UUID) ([]AnalyticsSiteStat, error) {
	rows, err := q.db.QueryContext(ctx, backupGetAnalyticsSiteStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsSiteStat
	for rows.Next() {
		var i AnalyticsSiteStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
			&i.AnalyticsType,
			&i.Impressions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetExclusionsForUser = `-- name: BackupGetExclusionsForUser :many
SELECT e.id, e.created_at, e.source_id, e.network_internal_id FROM exclusions e
JOIN sources s ON e.source_id = s.id
WHERE s.user_id = $1
`

func (q *Queries) BackupGetExclusionsForUser(ctx context.Context, userID uuid.UUID) ([]Exclusion, error) {
	rows, err := q.db.QueryContext(ctx, backupGetExclusionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exclusion
	for rows.Next() {
		var i Exclusion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SourceID,
			&i.NetworkInternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetPostTagsForUser = `-- name: BackupGetPostTagsForUser :many
SELECT pt.id, pt.created_at, pt.post_id, pt.tag_id FROM post_tags pt
JOIN posts p ON pt.post_id = p.id
JOIN sources s ON p.source_id = s.id
WHERE s.user_id = $1
`

func (q *Queries) BackupGetPostTagsForUser(ctx context.Context, userID uuid.UUID) ([]PostTag, error) {
	rows, err := q.db.QueryContext(ctx, backupGetPostTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostTag
	for rows.Next() {
		var i PostTag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.PostID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetPostsForUser = `-- name: BackupGetPostsForUser :many
SELECT p.id, p.created_at, p.last_synced_at, p.source_id, p.is_archived, p.network_internal_id, p.post_type, p.author, p.content FROM posts p
JOIN sources s ON p.source_id = s.id
WHERE s.user_id = $1
ORDER BY p.created_at
`

func (q *Queries) BackupGetPostsForUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, backupGetPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSyncedAt,
			&i.SourceID,
			&i.IsArchived,
			&i.NetworkInternalID,
			&i.PostType,
			&i.Author,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetReactionsForUser = `-- name: BackupGetReactionsForUser :many
SELECT prh.id, prh.synced_at, prh.post_id, prh.likes, prh.reposts, prh.views FROM posts_reactions_history prh
JOIN posts p ON prh.post_id = p.id
JOIN sources s ON p.source_id = s.id
WHERE s.user_id = $1
ORDER BY prh.synced_at
`

func (q *Queries) BackupGetReactionsForUser(ctx context.Context, userID uuid.UUID) ([]PostsReactionsHistory, error) {
	rows, err := q.db.QueryContext(ctx, backupGetReactionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostsReactionsHistory
	for rows.Next() {
		var i PostsReactionsHistory
		if err := rows.Scan(
			&i.ID,
			&i.SyncedAt,
			&i.PostID,
			&i.Likes,
			&i.Reposts,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetRedirectsForUser = `-- name: BackupGetRedirectsForUser :many
SELECT r.id, r.source_id, r.from_path, r.to_path, r.created_at FROM redirects r
JOIN sources s ON r.source_id = s.id
WHERE s.user_id = $1
`

func (q *Queries) BackupGetRedirectsForUser(ctx context.Context, userID uuid.UUID) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, backupGetRedirectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.FromPath,
			&i.ToPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetSourcesForUser = `-- name: BackupGetSourcesForUser :many
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced FROM sources WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) BackupGetSourcesForUser(ctx context.Context, userID uuid.UUID) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, backupGetSourcesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
			&i.UserName,
			&i.UserID,
			&i.IsActive,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetSourcesStatsForUser = `-- name: BackupGetSourcesStatsForUser :many
SELECT ss.id, ss.date, ss.source_id, ss.followers_count, ss.following_count, ss.posts_count, ss.average_likes, ss.average_reposts, ss.average_views FROM sources_stats ss
JOIN sources s ON ss.source_id = s.id
WHERE s.user_id = $1
ORDER BY ss.date
`

func (q *Queries) BackupGetSourcesStatsForUser(ctx context.Context, userID uuid.UUID) ([]SourcesStat, error) {
	rows, err := q.db.QueryContext(ctx, backupGetSourcesStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourcesStat
	for rows.Next() {
		var i SourcesStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SourceID,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.PostsCount,
			&i.AverageLikes,
			&i.AverageReposts,
			&i.AverageViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetTagClassificationsForUser = `-- name: BackupGetTagClassificationsForUser :many
SELECT id, created_at, updated_at, user_id, name FROM tag_classifications WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) BackupGetTagClassificationsForUser(ctx context.Context, userID uuid.UUID) ([]TagClassification, error) {
	rows, err := q.db.QueryContext(ctx, backupGetTagClassificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagClassification
	for rows.Next() {
		var i TagClassification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetTagsForUser = `-- name: BackupGetTagsForUser :many
SELECT id, created_at, updated_at, user_id, classification_id, name FROM tags WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) BackupGetTagsForUser(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, backupGetTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClassificationID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetTargetsForUser = `-- name: BackupGetTargetsForUser :many
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url FROM targets WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) BackupGetTargetsForUser(ctx context.Context, userID uuid.UUID) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, backupGetTargetsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetType,
			&i.UserID,
			&i.DbID,
			&i.IsActive,
			&i.SyncFrequency,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
			&i.HostUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetTokensForUser = `-- name: BackupGetTokensForUser :many
SELECT t.id, t.encrypted_access_token, t.nonce, t.created_at, t.updated_at, t.profile_id, t.source_id, t.target_id, t.source_app_data FROM tokens t
LEFT JOIN sources s ON t.source_id = s.id
LEFT JOIN targets tgt ON t.target_id = tgt.id
WHERE s.user_id = $1 OR tgt.user_id = $1
ORDER BY t.created_at
`

func (q *Queries) BackupGetTokensForUser(ctx context.Context, userID uuid.UUID) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, backupGetTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.EncryptedAccessToken,
			&i.Nonce,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileID,
			&i.SourceID,
			&i.TargetID,
			&i.SourceAppData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupGetUser = `-- name: BackupGetUser :one
SELECT id, username, created_at, updated_at, sync_period, profile_image,
       last_seen_version, intro_completed
FROM users WHERE id = $1
`

type BackupGetUserRow struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SyncPeriod      string         `json:"sync_period"`
	ProfileImage    sql.NullString `json:"profile_image"`
	LastSeenVersion string         `json:"last_seen_version"`
	IntroCompleted  bool           `json:"intro_completed"`
}

func (q *Queries) BackupGetUser(ctx context.Context, id uuid.UUID) (BackupGetUserRow, error) {
	row := q.db.QueryRowContext(ctx, backupGetUser, id)
	var i BackupGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.ProfileImage,
		&i.LastSeenVersion,
		&i.IntroCompleted,
	)
	return i, err
}
