// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mappings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMappingForColumn = `-- name: CreateMappingForColumn :one
INSERT INTO column_mappings (id, created_at, table_mapping_id, source_column_name, target_column_name, target_column_code)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, table_mapping_id, source_column_name, target_column_name, target_column_code
`

type CreateMappingForColumnParams struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	TableMappingID   uuid.UUID
	SourceColumnName string
	TargetColumnName string
	TargetColumnCode sql.NullString
}

func (q *Queries) CreateMappingForColumn(ctx context.Context, arg CreateMappingForColumnParams) (ColumnMapping, error) {
	row := q.db.QueryRowContext(ctx, createMappingForColumn,
		arg.ID,
		arg.CreatedAt,
		arg.TableMappingID,
		arg.SourceColumnName,
		arg.TargetColumnName,
		arg.TargetColumnCode,
	)
	var i ColumnMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TableMappingID,
		&i.SourceColumnName,
		&i.TargetColumnName,
		&i.TargetColumnCode,
	)
	return i, err
}

const createMappingForTable = `-- name: CreateMappingForTable :one
INSERT INTO table_mappings (id, created_at, source_table_name, target_table_name, target_table_code, target_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, source_table_name, target_table_name, target_table_code, target_id
`

type CreateMappingForTableParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	SourceTableName string
	TargetTableName string
	TargetTableCode sql.NullString
	TargetID        uuid.UUID
}

func (q *Queries) CreateMappingForTable(ctx context.Context, arg CreateMappingForTableParams) (TableMapping, error) {
	row := q.db.QueryRowContext(ctx, createMappingForTable,
		arg.ID,
		arg.CreatedAt,
		arg.SourceTableName,
		arg.TargetTableName,
		arg.TargetTableCode,
		arg.TargetID,
	)
	var i TableMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceTableName,
		&i.TargetTableName,
		&i.TargetTableCode,
		&i.TargetID,
	)
	return i, err
}
