// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AnalyticsPageStat struct {
	ID            uuid.UUID     `json:"id"`
	Date          time.Time     `json:"date"`
	UrlPath       string        `json:"url_path"`
	Views         int64         `json:"views"`
	SourceID      uuid.UUID     `json:"source_id"`
	AnalyticsType string        `json:"analytics_type"`
	Impressions   sql.NullInt64 `json:"impressions"`
}

type AnalyticsPageStatsOnTarget struct {
	ID             uuid.UUID     `json:"id"`
	SyncedAt       time.Time     `json:"synced_at"`
	StatID         uuid.NullUUID `json:"stat_id"`
	TargetID       uuid.UUID     `json:"target_id"`
	TargetRecordID string        `json:"target_record_id"`
}

type AnalyticsSiteStat struct {
	ID                 uuid.UUID     `json:"id"`
	Date               time.Time     `json:"date"`
	Visitors           int64         `json:"visitors"`
	AvgSessionDuration float64       `json:"avg_session_duration"`
	SourceID           uuid.UUID     `json:"source_id"`
	AnalyticsType      string        `json:"analytics_type"`
	Impressions        sql.NullInt64 `json:"impressions"`
}

type AnalyticsSiteStatsOnTarget struct {
	ID             uuid.UUID     `json:"id"`
	SyncedAt       time.Time     `json:"synced_at"`
	StatID         uuid.NullUUID `json:"stat_id"`
	TargetID       uuid.UUID     `json:"target_id"`
	TargetRecordID string        `json:"target_record_id"`
}

type AppConfig struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ColumnMapping struct {
	ID               uuid.UUID      `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	TableMappingID   uuid.UUID      `json:"table_mapping_id"`
	SourceColumnName string         `json:"source_column_name"`
	TargetColumnName string         `json:"target_column_name"`
	TargetColumnCode sql.NullString `json:"target_column_code"`
}

type Exclusion struct {
	ID                uuid.UUID `json:"id"`
	CreatedAt         time.Time `json:"created_at"`
	SourceID          uuid.UUID `json:"source_id"`
	NetworkInternalID string    `json:"network_internal_id"`
}

type Export struct {
	ID            uuid.UUID      `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	CompletedAt   time.Time      `json:"completed_at"`
	ExportStatus  string         `json:"export_status"`
	StatusMessage sql.NullString `json:"status_message"`
	UserID        uuid.UUID      `json:"user_id"`
	DownloadUrl   sql.NullString `json:"download_url"`
	ExportMethod  string         `json:"export_method"`
	TargetID      uuid.NullUUID  `json:"target_id"`
}

type Log struct {
	ID          uuid.UUID     `json:"id"`
	CreatedAt   time.Time     `json:"created_at"`
	SourceID    uuid.NullUUID `json:"source_id"`
	TargetID    uuid.NullUUID `json:"target_id"`
	Message     string        `json:"message"`
	IsDismissed bool          `json:"is_dismissed"`
}

type Post struct {
	ID                uuid.UUID      `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	LastSyncedAt      time.Time      `json:"last_synced_at"`
	SourceID          uuid.UUID      `json:"source_id"`
	IsArchived        bool           `json:"is_archived"`
	NetworkInternalID string         `json:"network_internal_id"`
	PostType          string         `json:"post_type"`
	Author            string         `json:"author"`
	Content           sql.NullString `json:"content"`
}

type PostsOnTarget struct {
	ID            uuid.UUID     `json:"id"`
	FirstSyncedAt time.Time     `json:"first_synced_at"`
	PostID        uuid.NullUUID `json:"post_id"`
	TargetID      uuid.UUID     `json:"target_id"`
	TargetPostID  string        `json:"target_post_id"`
}

type PostsReactionsHistory struct {
	ID       uuid.UUID     `json:"id"`
	SyncedAt time.Time     `json:"synced_at"`
	PostID   uuid.UUID     `json:"post_id"`
	Likes    sql.NullInt64 `json:"likes"`
	Reposts  sql.NullInt64 `json:"reposts"`
	Views    sql.NullInt64 `json:"views"`
}

type Redirect struct {
	ID        uuid.UUID `json:"id"`
	SourceID  uuid.UUID `json:"source_id"`
	FromPath  string    `json:"from_path"`
	ToPath    string    `json:"to_path"`
	CreatedAt time.Time `json:"created_at"`
}

type Source struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Network      string         `json:"network"`
	UserName     string         `json:"user_name"`
	UserID       uuid.UUID      `json:"user_id"`
	IsActive     bool           `json:"is_active"`
	SyncStatus   string         `json:"sync_status"`
	StatusReason sql.NullString `json:"status_reason"`
	LastSynced   sql.NullTime   `json:"last_synced"`
}

type SourcesOnTarget struct {
	ID             uuid.UUID `json:"id"`
	SourceID       uuid.UUID `json:"source_id"`
	TargetID       uuid.UUID `json:"target_id"`
	TargetSourceID string    `json:"target_source_id"`
}

type SourcesStat struct {
	ID             uuid.UUID       `json:"id"`
	Date           time.Time       `json:"date"`
	SourceID       uuid.UUID       `json:"source_id"`
	FollowersCount sql.NullInt64   `json:"followers_count"`
	FollowingCount sql.NullInt64   `json:"following_count"`
	PostsCount     sql.NullInt64   `json:"posts_count"`
	AverageLikes   sql.NullFloat64 `json:"average_likes"`
	AverageReposts sql.NullFloat64 `json:"average_reposts"`
	AverageViews   sql.NullFloat64 `json:"average_views"`
}

type SourcesStatsOnTarget struct {
	ID             uuid.UUID `json:"id"`
	SyncedAt       time.Time `json:"synced_at"`
	StatID         uuid.UUID `json:"stat_id"`
	TargetID       uuid.UUID `json:"target_id"`
	TargetRecordID string    `json:"target_record_id"`
}

type TableMapping struct {
	ID              uuid.UUID      `json:"id"`
	CreatedAt       time.Time      `json:"created_at"`
	SourceTableName string         `json:"source_table_name"`
	TargetTableName string         `json:"target_table_name"`
	TargetTableCode sql.NullString `json:"target_table_code"`
	TargetID        uuid.UUID      `json:"target_id"`
}

type Target struct {
	ID            uuid.UUID      `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	TargetType    string         `json:"target_type"`
	UserID        uuid.UUID      `json:"user_id"`
	DbID          sql.NullString `json:"db_id"`
	IsActive      bool           `json:"is_active"`
	SyncFrequency string         `json:"sync_frequency"`
	SyncStatus    string         `json:"sync_status"`
	StatusReason  sql.NullString `json:"status_reason"`
	LastSynced    sql.NullTime   `json:"last_synced"`
	HostUrl       sql.NullString `json:"host_url"`
}

type Token struct {
	ID                   uuid.UUID       `json:"id"`
	EncryptedAccessToken []byte          `json:"encrypted_access_token"`
	Nonce                []byte          `json:"nonce"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	ProfileID            sql.NullString  `json:"profile_id"`
	SourceID             uuid.NullUUID   `json:"source_id"`
	TargetID             uuid.NullUUID   `json:"target_id"`
	SourceAppData        json.RawMessage `json:"source_app_data"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SyncPeriod      string         `json:"sync_period"`
	PasswordHash    sql.NullString `json:"password_hash"`
	TotpSecret      sql.NullString `json:"totp_secret"`
	TotpEnabled     sql.NullBool   `json:"totp_enabled"`
	ProfileImage    sql.NullString `json:"profile_image"`
	LastSeenVersion string         `json:"last_seen_version"`
	IntroCompleted  bool           `json:"intro_completed"`
}

type WebauthnCredential struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
	CredentialID    []byte        `json:"credential_id"`
	PublicKey       []byte        `json:"public_key"`
	AttestationType string        `json:"attestation_type"`
	Aaguid          uuid.NullUUID `json:"aaguid"`
	SignCount       sql.NullInt64 `json:"sign_count"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}
