// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_tags.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addTagToPost = `-- name: AddTagToPost :one
INSERT INTO
    post_tags (id, created_at, post_id, tag_id)
VALUES ($1, $2, $3, $4)
RETURNING
    id, created_at, post_id, tag_id
`

type AddTagToPostParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	PostID    uuid.UUID `json:"post_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) (PostTag, error) {
	row := q.db.QueryRowContext(ctx, addTagToPost,
		arg.ID,
		arg.CreatedAt,
		arg.PostID,
		arg.TagID,
	)
	var i PostTag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PostID,
		&i.TagID,
	)
	return i, err
}

const clearTagsForPost = `-- name: ClearTagsForPost :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) ClearTagsForPost(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearTagsForPost, postID)
	return err
}

const getAllPostTagsForUser = `-- name: GetAllPostTagsForUser :many
SELECT pt.post_id,
    t.id as tag_id,
    t.name as tag_name,
    tc.name as classification_name
FROM post_tags pt
    JOIN tags t ON pt.tag_id = t.id
    LEFT JOIN tag_classifications tc ON t.classification_id = tc.id
    JOIN posts p ON pt.post_id = p.id
    JOIN sources s ON p.source_id = s.id
WHERE
    s.user_id = $1
ORDER BY tc.name ASC NULLS LAST, t.name ASC
`

type GetAllPostTagsForUserRow struct {
	PostID             uuid.UUID      `json:"post_id"`
	TagID              uuid.UUID      `json:"tag_id"`
	TagName            string         `json:"tag_name"`
	ClassificationName sql.NullString `json:"classification_name"`
}

func (q *Queries) GetAllPostTagsForUser(ctx context.Context, userID uuid.UUID) ([]GetAllPostTagsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostTagsForUserRow
	for rows.Next() {
		var i GetAllPostTagsForUserRow
		if err := rows.Scan(
			&i.PostID,
			&i.TagID,
			&i.TagName,
			&i.ClassificationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostIdsWithNoTags = `-- name: GetPostIdsWithNoTags :many
SELECT p.id as post_id
FROM posts p
    JOIN sources s ON p.source_id = s.id
    LEFT JOIN post_tags pt ON p.id = pt.post_id
WHERE
    s.user_id = $1
    AND pt.id IS NULL
`

func (q *Queries) GetPostIdsWithNoTags(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getPostIdsWithNoTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var post_id uuid.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForPost = `-- name: GetTagsForPost :many
SELECT t.id,
    t.name,
    t.classification_id,
    tc.name as classification_name
FROM post_tags pt
    JOIN tags t ON pt.tag_id = t.id
    LEFT JOIN tag_classifications tc ON t.classification_id = tc.id
WHERE
    pt.post_id = $1
ORDER BY tc.name ASC NULLS LAST, t.name ASC
`

type GetTagsForPostRow struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	ClassificationID   uuid.NullUUID  `json:"classification_id"`
	ClassificationName sql.NullString `json:"classification_name"`
}

func (q *Queries) GetTagsForPost(ctx context.Context, postID uuid.UUID) ([]GetTagsForPostRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsForPostRow
	for rows.Next() {
		var i GetTagsForPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClassificationID,
			&i.ClassificationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromPost = `-- name: RemoveTagFromPost :exec
DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2
`

type RemoveTagFromPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPost, arg.PostID, arg.TagID)
	return err
}
