// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveUnsyncedPosts = `-- name: ArchiveUnsyncedPosts :exec
UPDATE posts
SET
    is_archived = true
WHERE
    source_id = $1
    AND last_synced_at < $2
`

type ArchiveUnsyncedPostsParams struct {
	SourceID     uuid.UUID `json:"source_id"`
	LastSyncedAt time.Time `json:"last_synced_at"`
}

func (q *Queries) ArchiveUnsyncedPosts(ctx context.Context, arg ArchiveUnsyncedPostsParams) error {
	_, err := q.db.ExecContext(ctx, archiveUnsyncedPosts, arg.SourceID, arg.LastSyncedAt)
	return err
}

const checkCountOfPostsForUser = `-- name: CheckCountOfPostsForUser :one
SELECT COUNT(*)
FROM posts p
    join sources s on p.source_id = s.id
where
    s.user_id = $1
`

func (q *Queries) CheckCountOfPostsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCountOfPostsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO
    posts (
        id,
        created_at,
        last_synced_at,
        source_id,
        is_archived,
        network_internal_id,
        content,
        post_type,
        author
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, created_at, last_synced_at, source_id, is_archived, network_internal_id, post_type, author, content
`

type CreatePostParams struct {
	ID                uuid.UUID      `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	LastSyncedAt      time.Time      `json:"last_synced_at"`
	SourceID          uuid.UUID      `json:"source_id"`
	IsArchived        bool           `json:"is_archived"`
	NetworkInternalID string         `json:"network_internal_id"`
	Content           sql.NullString `json:"content"`
	PostType          string         `json:"post_type"`
	Author            string         `json:"author"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.LastSyncedAt,
		arg.SourceID,
		arg.IsArchived,
		arg.NetworkInternalID,
		arg.Content,
		arg.PostType,
		arg.Author,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.SourceID,
		&i.IsArchived,
		&i.NetworkInternalID,
		&i.PostType,
		&i.Author,
		&i.Content,
	)
	return i, err
}

const deletePostsByNetworkIdPrefix = `-- name: DeletePostsByNetworkIdPrefix :exec
DELETE FROM posts
WHERE
    source_id = $1
    AND network_internal_id LIKE $2
`

type DeletePostsByNetworkIdPrefixParams struct {
	SourceID          uuid.UUID `json:"source_id"`
	NetworkInternalID string    `json:"network_internal_id"`
}

func (q *Queries) DeletePostsByNetworkIdPrefix(ctx context.Context, arg DeletePostsByNetworkIdPrefixParams) error {
	_, err := q.db.ExecContext(ctx, deletePostsByNetworkIdPrefix, arg.SourceID, arg.NetworkInternalID)
	return err
}

const getAllPostsWithTheLatestInfoForUser = `-- name: GetAllPostsWithTheLatestInfoForUser :many
SELECT
    p.id,
    p.created_at,
    p.source_id,
    p.is_archived,
    p.network_internal_id,
    p.content,
    p.post_type,
    p.author,
    s.network AS network,
    u.username AS current_user_name,
    s.user_name AS source_user_name,
    r.synced_at AS reactions_synced_at,
    r.likes,
    r.reposts,
    r.views
FROM
    posts p
    left join sources s ON p.source_id = s.id
    left join users u on s.user_id = u.id
    LEFT JOIN posts_reactions_history r ON r.post_id = p.id
    AND r.synced_at = (
        SELECT MAX(prh.synced_at)
        FROM posts_reactions_history prh
        WHERE
            prh.post_id = p.id
    )
WHERE
    s.user_id = $1
`

type GetAllPostsWithTheLatestInfoForUserRow struct {
	ID                uuid.UUID      `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	SourceID          uuid.UUID      `json:"source_id"`
	IsArchived        bool           `json:"is_archived"`
	NetworkInternalID string         `json:"network_internal_id"`
	Content           sql.NullString `json:"content"`
	PostType          string         `json:"post_type"`
	Author            string         `json:"author"`
	Network           sql.NullString `json:"network"`
	CurrentUserName   sql.NullString `json:"current_user_name"`
	SourceUserName    sql.NullString `json:"source_user_name"`
	ReactionsSyncedAt sql.NullTime   `json:"reactions_synced_at"`
	Likes             sql.NullInt64  `json:"likes"`
	Reposts           sql.NullInt64  `json:"reposts"`
	Views             sql.NullInt64  `json:"views"`
}

func (q *Queries) GetAllPostsWithTheLatestInfoForUser(ctx context.Context, userID uuid.UUID) ([]GetAllPostsWithTheLatestInfoForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostsWithTheLatestInfoForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsWithTheLatestInfoForUserRow
	for rows.Next() {
		var i GetAllPostsWithTheLatestInfoForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SourceID,
			&i.IsArchived,
			&i.NetworkInternalID,
			&i.Content,
			&i.PostType,
			&i.Author,
			&i.Network,
			&i.CurrentUserName,
			&i.SourceUserName,
			&i.ReactionsSyncedAt,
			&i.Likes,
			&i.Reposts,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostBySourceAndNetworkId = `-- name: GetPostBySourceAndNetworkId :one
SELECT posts.id, posts.created_at, posts.last_synced_at, posts.source_id, posts.is_archived, posts.network_internal_id, posts.post_type, posts.author, posts.content
FROM posts
where
    network_internal_id = $1
    and source_id = $2
`

type GetPostBySourceAndNetworkIdParams struct {
	NetworkInternalID string    `json:"network_internal_id"`
	SourceID          uuid.UUID `json:"source_id"`
}

func (q *Queries) GetPostBySourceAndNetworkId(ctx context.Context, arg GetPostBySourceAndNetworkIdParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySourceAndNetworkId, arg.NetworkInternalID, arg.SourceID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.SourceID,
		&i.IsArchived,
		&i.NetworkInternalID,
		&i.PostType,
		&i.Author,
		&i.Content,
	)
	return i, err
}

const getRecentPostsForUser = `-- name: GetRecentPostsForUser :many
SELECT
    p.created_at,
    p.network_internal_id,
    p.content,
    p.post_type,
    p.author,
    p.is_archived,
    p.source_id,
    s.network AS network,
    r.likes,
    r.reposts,
    (
        COALESCE(r.likes, 0) + COALESCE(r.reposts, 0)
    )::bigint AS interactions,
    r.views
FROM
    posts p
    left join sources s ON p.source_id = s.id
    LEFT JOIN posts_reactions_history r ON r.post_id = p.id
    AND r.synced_at = (
        SELECT MAX(prh.synced_at)
        FROM posts_reactions_history prh
        WHERE
            prh.post_id = p.id
    )
WHERE
    s.user_id = $1
ORDER BY p.created_at DESC
LIMIT 10000
`

type GetRecentPostsForUserRow struct {
	CreatedAt         time.Time      `json:"created_at"`
	NetworkInternalID string         `json:"network_internal_id"`
	Content           sql.NullString `json:"content"`
	PostType          string         `json:"post_type"`
	Author            string         `json:"author"`
	IsArchived        bool           `json:"is_archived"`
	SourceID          uuid.UUID      `json:"source_id"`
	Network           sql.NullString `json:"network"`
	Likes             sql.NullInt64  `json:"likes"`
	Reposts           sql.NullInt64  `json:"reposts"`
	Interactions      int64          `json:"interactions"`
	Views             sql.NullInt64  `json:"views"`
}

func (q *Queries) GetRecentPostsForUser(ctx context.Context, userID uuid.UUID) ([]GetRecentPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPostsForUserRow
	for rows.Next() {
		var i GetRecentPostsForUserRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.NetworkInternalID,
			&i.Content,
			&i.PostType,
			&i.Author,
			&i.IsArchived,
			&i.SourceID,
			&i.Network,
			&i.Likes,
			&i.Reposts,
			&i.Interactions,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    last_synced_at = $2,
    is_archived = $3,
    content = $4,
    post_type = $5,
    author = $6
WHERE
    id = $1
RETURNING
    id, created_at, last_synced_at, source_id, is_archived, network_internal_id, post_type, author, content
`

type UpdatePostParams struct {
	ID           uuid.UUID      `json:"id"`
	LastSyncedAt time.Time      `json:"last_synced_at"`
	IsArchived   bool           `json:"is_archived"`
	Content      sql.NullString `json:"content"`
	PostType     string         `json:"post_type"`
	Author       string         `json:"author"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.LastSyncedAt,
		arg.IsArchived,
		arg.Content,
		arg.PostType,
		arg.Author,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.SourceID,
		&i.IsArchived,
		&i.NetworkInternalID,
		&i.PostType,
		&i.Author,
		&i.Content,
	)
	return i, err
}
