// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_classifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTagClassification = `-- name: CreateTagClassification :one
INSERT INTO
    tag_classifications (
        id,
        created_at,
        updated_at,
        user_id,
        name
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, created_at, updated_at, user_id, name
`

type CreateTagClassificationParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateTagClassification(ctx context.Context, arg CreateTagClassificationParams) (TagClassification, error) {
	row := q.db.QueryRowContext(ctx, createTagClassification,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Name,
	)
	var i TagClassification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
	)
	return i, err
}

const deleteTagClassification = `-- name: DeleteTagClassification :exec
DELETE FROM tag_classifications WHERE id = $1
`

func (q *Queries) DeleteTagClassification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTagClassification, id)
	return err
}

const getTagClassificationById = `-- name: GetTagClassificationById :one
SELECT id, created_at, updated_at, user_id, name
FROM tag_classifications
WHERE
    id = $1
`

func (q *Queries) GetTagClassificationById(ctx context.Context, id uuid.UUID) (TagClassification, error) {
	row := q.db.QueryRowContext(ctx, getTagClassificationById, id)
	var i TagClassification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
	)
	return i, err
}

const getTagClassificationsForUser = `-- name: GetTagClassificationsForUser :many
SELECT id, created_at, updated_at, user_id, name
FROM tag_classifications
WHERE
    user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTagClassificationsForUser(ctx context.Context, userID uuid.UUID) ([]TagClassification, error) {
	rows, err := q.db.QueryContext(ctx, getTagClassificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagClassification
	for rows.Next() {
		var i TagClassification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagClassification = `-- name: UpdateTagClassification :one
UPDATE tag_classifications
SET
    name = $2,
    updated_at = $3
WHERE
    id = $1
RETURNING
    id, created_at, updated_at, user_id, name
`

type UpdateTagClassificationParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTagClassification(ctx context.Context, arg UpdateTagClassificationParams) (TagClassification, error) {
	row := q.db.QueryRowContext(ctx, updateTagClassification, arg.ID, arg.Name, arg.UpdatedAt)
	var i TagClassification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
	)
	return i, err
}
