// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTag = `-- name: CreateTag :one
INSERT INTO
    tags (
        id,
        created_at,
        updated_at,
        user_id,
        classification_id,
        name
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, created_at, updated_at, user_id, classification_id, name
`

type CreateTagParams struct {
	ID               uuid.UUID     `json:"id"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	UserID           uuid.UUID     `json:"user_id"`
	ClassificationID uuid.NullUUID `json:"classification_id"`
	Name             string        `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ClassificationID,
		arg.Name,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ClassificationID,
		&i.Name,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagById = `-- name: GetTagById :one
SELECT id, created_at, updated_at, user_id, classification_id, name
FROM tags
WHERE
    id = $1
`

func (q *Queries) GetTagById(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagById, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ClassificationID,
		&i.Name,
	)
	return i, err
}

const getTagsForClassification = `-- name: GetTagsForClassification :many
SELECT id, created_at, updated_at, user_id, classification_id, name
FROM tags
WHERE
    classification_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTagsForClassification(ctx context.Context, classificationID uuid.NullUUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForClassification, classificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClassificationID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForUser = `-- name: GetTagsForUser :many
SELECT t.id,
    t.created_at,
    t.updated_at,
    t.user_id,
    t.classification_id,
    t.name,
    tc.name as classification_name
FROM tags t
    LEFT JOIN tag_classifications tc ON t.classification_id = tc.id
WHERE
    t.user_id = $1
ORDER BY tc.name ASC NULLS LAST, t.name ASC
`

type GetTagsForUserRow struct {
	ID                 uuid.UUID      `json:"id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	UserID             uuid.UUID      `json:"user_id"`
	ClassificationID   uuid.NullUUID  `json:"classification_id"`
	Name               string         `json:"name"`
	ClassificationName sql.NullString `json:"classification_name"`
}

func (q *Queries) GetTagsForUser(ctx context.Context, userID uuid.UUID) ([]GetTagsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsForUserRow
	for rows.Next() {
		var i GetTagsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClassificationID,
			&i.Name,
			&i.ClassificationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnclassifiedTagsForUser = `-- name: GetUnclassifiedTagsForUser :many
SELECT id, created_at, updated_at, user_id, classification_id, name
FROM tags
WHERE
    user_id = $1
    AND classification_id IS NULL
ORDER BY name ASC
`

func (q *Queries) GetUnclassifiedTagsForUser(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getUnclassifiedTagsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ClassificationID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET
    name = $2,
    updated_at = $3,
    classification_id = $4
WHERE
    id = $1
RETURNING
    id, created_at, updated_at, user_id, classification_id, name
`

type UpdateTagParams struct {
	ID               uuid.UUID     `json:"id"`
	Name             string        `json:"name"`
	UpdatedAt        time.Time     `json:"updated_at"`
	ClassificationID uuid.NullUUID `json:"classification_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.UpdatedAt,
		arg.ClassificationID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ClassificationID,
		&i.Name,
	)
	return i, err
}
