// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO
    tokens (
        id,
        encrypted_access_token,
        nonce,
        created_at,
        updated_at,
        source_id,
        target_id,
        profile_id,
        source_app_data
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, encrypted_access_token, nonce, created_at, updated_at, profile_id, source_id, target_id, source_app_data
`

type CreateTokenParams struct {
	ID                   uuid.UUID       `json:"id"`
	EncryptedAccessToken []byte          `json:"encrypted_access_token"`
	Nonce                []byte          `json:"nonce"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	SourceID             uuid.NullUUID   `json:"source_id"`
	TargetID             uuid.NullUUID   `json:"target_id"`
	ProfileID            sql.NullString  `json:"profile_id"`
	SourceAppData        json.RawMessage `json:"source_app_data"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.EncryptedAccessToken,
		arg.Nonce,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SourceID,
		arg.TargetID,
		arg.ProfileID,
		arg.SourceAppData,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceAppData,
	)
	return i, err
}

const deleteTokenById = `-- name: DeleteTokenById :exec
DELETE FROM tokens WHERE id = $1
`

func (q *Queries) DeleteTokenById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTokenById, id)
	return err
}

const getTokenBySource = `-- name: GetTokenBySource :one
SELECT id, encrypted_access_token, nonce, created_at, updated_at, profile_id, source_id, target_id, source_app_data FROM tokens where source_id = $1
`

func (q *Queries) GetTokenBySource(ctx context.Context, sourceID uuid.NullUUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenBySource, sourceID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceAppData,
	)
	return i, err
}

const getTokenByTarget = `-- name: GetTokenByTarget :one
SELECT id, encrypted_access_token, nonce, created_at, updated_at, profile_id, source_id, target_id, source_app_data FROM tokens where target_id = $1
`

func (q *Queries) GetTokenByTarget(ctx context.Context, targetID uuid.NullUUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByTarget, targetID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.SourceID,
		&i.TargetID,
		&i.SourceAppData,
	)
	return i, err
}

const updateTokenProfile = `-- name: UpdateTokenProfile :exec
UPDATE tokens
SET
    profile_id = $2,
    updated_at = $3
WHERE
    id = $1
`

type UpdateTokenProfileParams struct {
	ID        uuid.UUID      `json:"id"`
	ProfileID sql.NullString `json:"profile_id"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateTokenProfile(ctx context.Context, arg UpdateTokenProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenProfile, arg.ID, arg.ProfileID, arg.UpdatedAt)
	return err
}
