// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (id, user_id, encrypted_access_token, nonce, created_at, updated_at, network)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, encrypted_access_token, nonce, created_at, updated_at, network
`

type CreateTokenParams struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	EncryptedAccessToken []byte
	Nonce                []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Network              string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.EncryptedAccessToken,
		arg.Nonce,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Network,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const getTokenByNetworkAndUser = `-- name: GetTokenByNetworkAndUser :one
SELECT id, user_id, encrypted_access_token, nonce, created_at, updated_at, network FROM tokens
where user_id = $1 and network = $2
`

type GetTokenByNetworkAndUserParams struct {
	UserID  uuid.UUID
	Network string
}

func (q *Queries) GetTokenByNetworkAndUser(ctx context.Context, arg GetTokenByNetworkAndUserParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByNetworkAndUser, arg.UserID, arg.Network)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}
